from os import path


def baseGen(cwd):
    return f"""# Autogenerated by artix-iso-util. Don't touch this
WORKSPACE_DIR={path.dirname(cwd)}
CHROOTS_DIR={path.join(cwd, "build")}
"""


def isoGen(cwd, version, init, comp, lvl):
    return f"""# Autogenerated by artix-iso-util. Don't touch this
ISO_POOL={path.join(cwd, "iso")}
ISO_VERSION={version}
INITSYS={init}
COMPRESSION={comp}
COMPRESSION_LEVEL={lvl}
"""
