from os import path


def baseGen(cwd):
    return f"""# Autogenerated by artix-iso-util. Don't touch this
WORKSPACE_DIR="{cwd}"
CHROOTS_DIR="{path.join(cwd, "build")}"
"""


def isoGen(cwd, version, init, comp, lvl):
    code = f"""# Autogenerated by artix-iso-util. Don't touch this
ISO_POOL="{path.join(cwd, "iso")}"
ISO_VERSION="{version}"
INITSYS="{init}"
COMPRESSION="{comp}"
"""
    code += f"COMPRESSION_LEVEL=\"{lvl}\"" if comp == "zstd" else ""
    return code
